### ISSUE TITLE
Deauth does not work for me...

### ISSUE THREAD

**Issue by sXrgi** [sankethj/ZiFi#2]
I installed the bin with ESPFlasher and the acces point works but when I enter to the interface, i can't deauth the router and create the evil twin.

**Comment by Scail-exe** [comment]
btw good work, keep working!!

**Comment by sankethj** [comment]
Only problem is deauth not working, 
Evil twin is working file, recheck again. If still also same problem then I'll change the bin file. 

I will fix deauth in next coming month ✌. Thank you.

**Comment by Scail-exe** [comment]
True, today Evil twin works for me.. but deauth still not working... Ill be waiting for next version. Good Work!!
